Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [6]:
import numpy as np

In [36]:
N = int(input("Введите N= "))
array = np.arange(N-1, -1, -1)
array

Введите N= 8


array([7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [38]:
N = int(input("Введите N:"))
a = np.diag(np.arange(0, N))
d =  sum(np.diag(a))
print(a)
print('Сумма диагонали: ',d)

Введите N:9
[[0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 5 0 0 0]
 [0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0 0 0 8]]
Сумма диагонали:  36


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [72]:
from numpy import linalg

In [8]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4, ] ] )

In [9]:
b = np.array( [4, 12, -3] )

In [10]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [11]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задание 4.

In [40]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [45]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])


2.23606797749979

In [74]:
def conus(p, r):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    pLength = np.linalg.norm(p)
    rLength = np.linalg.norm(r)
    
    return np.dot(p, r) / (pLength * rLength)

In [75]:
i = 0
slovar = {}
for user in users_stats:
    slovar[i] = conus(next_user_stats, user)
    i += 1
    pohoz = max(slovar, key = slovar.get)
print(f'Самый похожий пользователь: № {pohoz}')

Самый похожий пользователь: № 7
